#!/usr/bin/env bash

### BEGIN INIT INFO
# Provides:             correctdate
# Required-Start:       $local_fs
# Required-Stop:        $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Correct the date for python flask-login
### END INIT INFO

case "$1" in
    start)
        # fix the date problem
        year=$(date "+%Y")
        if [ "$year" == "2010" ]; then
            date -s "2012-01-01" &>/dev/null
        fi
        ;;
    *)
        ## If no parameters are given, print which are avaiable.
        echo "Usage: $0 {start}"
        exit 1
        ;;
esac

