#!/bin/sh

PATH=$PATH:/usr/ccs/bin:/usr/sfw/bin:/usr/local/bin

dir=./`uname -sm | sed -e 's/ /./g'`
if [ "X$1" != "X" ]; then
	dir=$1
	shift
fi

echo ======================
ldd    $dir/vncstorepw
ldd -r $dir/vncstorepw
echo ======================
echo
rm -f ./testfile2
$dir/vncstorepw qwerty ./testfile2
ls -l  ./testfile ./testfile2
sum    ./testfile ./testfile2
echo
echo diff ./testfile ./testfile2
echo ----------------------
     diff ./testfile ./testfile2
echo ----------------------

rm -f ./testfile2
